### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by YuriyTikhonoff** [YuriyTikhonoff/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Gorovoi-Artem** [comment]
My life is my kung fu to overcome the forces of evil. I gave a vouch to fight to my last  breath. Now the Devil representative with made up name Donald Trump is going to break the world order and push the backbone of democracy into the abyss of total chaos. My mission is to save the world from his adherent and spoil their riot.
