### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by YuriyTikhonoff** [YuriyTikhonoff/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Gorovoi-Artem** [comment]
Ryu the Brave. thelasthero@glorify.me whatsapp +1321777777 LA, California, the USA. Miracle lane 77 Postal code 74556

**Comment by YuriyTikhonoff** [comment]
Thanks bro
