### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by YuriyTikhonoff** [YuriyTikhonoff/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Gorovoi-Artem** [comment]
500 BC - The beginning of hero's activity, 200 BC  - Consulting ancient Greeks about the constrain strategy towards barbarians, 1100 AD - Opening Chinese office, 1300 - Establishing Shaolin temple as a training center, 1500 AD - Ending Dark Age in Europe and funding scientific research, 2021 AD - the Last Clash of Civilisations
